version: '3.8'

services:
  movies:
    build: .
    command: python ./src/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/:/code/src/
    ports:
      - 8009:8000
    env_file:
      - .env.dev
